export const SUPPORTED_LANGUES = [
  { title: "Afrikaans", code: "af" },
  { title: "Albanian", code: "sq" },
  { title: "Amharic", code: "am" },
  { title: "Arabic", code: "ar" },
  { title: "Armenian", code: "hy" },
  { title: "Azerbaijani", code: "az" },
  { title: "Basque", code: "eu" },
  { title: "Belarusian", code: "be" },
  { title: "Bengali", code: "bn" },
  { title: "Bosnian", code: "bs" },
  { title: "Bulgarian", code: "bg" },
  { title: "Catalan", code: "ca" },
  { title: "Cebuano", code: "ceb" },
  { title: "Chinese (Simplified)", code: "zh-CN" },
  { title: "Chinese (Traditional)", code: "zh-TW" },
  { title: "Corsican", code: "co" },
  { title: "Croatian", code: "hr" },
  { title: "Czech", code: "cs" },
  { title: "Danish", code: "da" },
  { title: "Dutch", code: "nl" },
  { title: "English", code: "en" },
  { title: "Esperanto", code: "eo" },
  { title: "Estonian", code: "et" },
  { title: "Finnish", code: "fi" },
  { title: "French", code: "fr" },
  { title: "Frisian", code: "fy" },
  { title: "Galician", code: "gl" },
  { title: "Georgian", code: "ka" },
  { title: "German", code: "de" },
  { title: "Greek", code: "el" },
  { title: "Gujarati", code: "gu" },
  { title: "Haitian Creole", code: "ht" },
  { title: "Hausa", code: "ha" },
  { title: "Hawaiian", code: "haw" },
  { title: "Hebrew", code: "he or iw" },
  { title: "Hindi", code: "hi" },
  { title: "Hmong", code: "hmn" },
  { title: "Hungarian", code: "hu" },
  { title: "Icelandic", code: "is" },
  { title: "Igbo", code: "ig" },
  { title: "Indonesian", code: "id" },
  { title: "Irish", code: "ga" },
  { title: "Italian", code: "it" },
  { title: "Japanese", code: "ja" },
  { title: "Javanese", code: "jv" },
  { title: "Kannada", code: "kn" },
  { title: "Kazakh", code: "kk" },
  { title: "Khmer", code: "km" },
  { title: "Kinyarwanda", code: "rw" },
  { title: "Korean", code: "ko" },
  { title: "Kurdish", code: "ku" },
  { title: "Kurdish (Sorani)", code: "ckb" },
  { title: "Kyrgyz", code: "ky" },
  { title: "Lao", code: "lo" },
  { title: "Latin", code: "la" },
  { title: "Latvian", code: "lv" },
  { title: "Lithuanian", code: "lt" },
  { title: "Luxembourgish", code: "lb" },
  { title: "Macedonian", code: "mk" },
  { title: "Malagasy", code: "mg" },
  { title: "Malay", code: "ms" },
  { title: "Malayalam", code: "ml" },
  { title: "Maltese", code: "mt" },
  { title: "Maori", code: "mi" },
  { title: "Marathi", code: "mr" },
  { title: "Mongolian", code: "mn" },
  { title: "Myanmar (Burmese)", code: "my" },
  { title: "Nepali", code: "ne" },
  { title: "Norwegian", code: "no" },
  { title: "Nyanja (Chichewa)", code: "ny" },
  { title: "Odia (Oriya)", code: "or" },
  { title: "Pashto", code: "ps" },
  { title: "Persian", code: "fa" },
  { title: "Polish", code: "pl" },
  { title: "Portuguese (Portugal, Brazil)", code: "pt" },
  { title: "Punjabi", code: "pa" },
  { title: "Romanian", code: "ro" },
  { title: "Russian", code: "ru" },
  { title: "Samoan", code: "sm" },
  { title: "Scots Gaelic", code: "gd" },
  { title: "Serbian", code: "sr" },
  { title: "Sesotho", code: "st" },
  { title: "Shona", code: "sn" },
  { title: "Sindhi", code: "sd" },
  { title: "Sinhala (Sinhalese)", code: "si" },
  { title: "Slovak", code: "sk" },
  { title: "Slovenian", code: "sl" },
  { title: "Somali", code: "so" },
  { title: "Spanish", code: "es" },
  { title: "Sundanese", code: "su" },
  { title: "Swahili", code: "sw" },
  { title: "Swedish", code: "sv" },
  { title: "Tagalog (Filipino)", code: "tl" },
  { title: "Tajik", code: "tg" },
  { title: "Tamil", code: "ta" },
  { title: "Tatar", code: "tt" },
  { title: "Telugu", code: "te" },
  { title: "Thai", code: "th" },
  { title: "Turkish", code: "tr" },
  { title: "Turkmen", code: "tk" },
  { title: "Ukrainian", code: "uk" },
  { title: "Urdu", code: "ur" },
  { title: "Uyghur", code: "ug" },
  { title: "Uzbek", code: "uz" },
  { title: "Vietnamese", code: "vi" },
  { title: "Welsh", code: "cy" },
  { title: "Xhosa", code: "xh" },
  { title: "Yiddish", code: "yi" },
  { title: "Yoruba", code: "yo" },
  { title: "Zulu", code: "zu" },
];
